language: node_js
node_js:
  - 10.16.3
env:
  global:
    - TRAVIS_PACKAGE_VERSION="0.1.$TRAVIS_BUILD_NUMBER"
    - TRAVIS_PACKAGE_FILE="$TRAVIS_BUILD_DIR/package_v$TRAVIS_PACKAGE_VERSION.zip"
    - SURGE_LOGIN=$SURGE_RELEASELOGIN
    - SURGE_TOKEN=$SURGE_RELEASETOKEN
    - BASEAPI_URL=$BASEAPI_URL
    
# blacklist
branches:
  except:
    - /untagged-.*/

notifications:
  email:
    on_success: always
    on_failure: always

before_deploy:
  - sed -i 's,https://localhost:44302/api,$BASEAPI_URL,' .env
  - npm run build
  - cd dist && zip -rv9 $TRAVIS_PACKAGE_FILE . && cd ..
deploy:
  - provider: surge
    project: ./dist/
    domain: https://buske-dev.surge.sh
    skip_cleanup: true
    on:      
      branch: master
      
  - provider: surge
    project: ./dist/
    domain: https://buske.surge.sh
    skip_cleanup: true
    on:      
      branch: release
  
  - provider: releases
    api_key: $GITHUBPAGES_RELEASETOKEN
    file: "$TRAVIS_PACKAGE_FILE"
    skip_cleanup: true
    name: "v$TRAVIS_PACKAGE_VERSION"
    draft: false
    on:      
      branch: release
after_deploy:
  - rm $TRAVIS_PACKAGE_FILE